CREATE TABLE PAI.FUNDING_TYPE_REF (
    FTR_CODE VARCHAR2(3 BYTE),
    FTR_DESCRIPTION VARCHAR2(300),
    FTR_CREATED_BY VARCHAR2(30 BYTE) DEFAULT USER,
    FTR_CREATED_DATE DATE DEFAULT SYSDATE,
    FTR_UPDATED_BY VARCHAR2(30 BYTE) DEFAULT USER,
    FTR_UPDATED_DATE DATE DEFAULT SYSDATE
)

INSERT ALL
    INTO PAI.FUNDING_TYPE_REF (FTR_CODE, FTR_DESCRIPTION, FTR_CREATED_BY, FTR_UPDATED_BY) VALUES ('COM', 'Community Rated', 'APR0165298', 'APR0165298')
    INTO PAI.FUNDING_TYPE_REF (FTR_CODE, FTR_DESCRIPTION, FTR_CREATED_BY, FTR_UPDATED_BY) VALUES ('EXP', 'Experience Rated', 'APR0165298', 'APR0165298')
    INTO PAI.FUNDING_TYPE_REF (FTR_CODE, FTR_DESCRIPTION, FTR_CREATED_BY, FTR_UPDATED_BY) VALUES ('LVL', 'Level Funded', 'APR0165298', 'APR0165298')
    INTO PAI.FUNDING_TYPE_REF (FTR_CODE, FTR_DESCRIPTION, FTR_CREATED_BY, FTR_UPDATED_BY) VALUES ('SFD', 'Self Funded', 'APR0165298', 'APR0165298')
    INTO PAI.FUNDING_TYPE_REF (FTR_CODE, FTR_DESCRIPTION, FTR_CREATED_BY, FTR_UPDATED_BY) VALUES ('RBP', 'Reference Based Pricing', 'APR0165298', 'APR0165298')
    INTO PAI.FUNDING_TYPE_REF (FTR_CODE, FTR_DESCRIPTION, FTR_CREATED_BY, FTR_UPDATED_BY) VALUES ('OTH', 'Other', 'APR0165298', 'APR0165298')
    INTO PAI.FUNDING_TYPE_REF (FTR_CODE, FTR_DESCRIPTION, FTR_CREATED_BY, FTR_UPDATED_BY) VALUES ('UND', 'Undefined', 'APR0165298', 'APR0165298')
SELECT * FROM dual;
